### ISSUE TITLE
create an "Overview of Changes" page

### ISSUE THREAD

**Issue by erinzstrenio** [18F/cms-carts-seds#108]
summarize major changes to CARTS on one page for state users

**Comment by cannandev** [comment]
Linked to #111

**Comment by erinzstrenio** [comment]
This may no longer be necessary with the launch emails summarizing the new CARTS features

**Comment by austinhernandez** [comment]
Here is this ticket as a story:

As a **state user**, I need to **know what changes have been made since the previous reporting period** so that I can **avoid errors, reduce questions for DSCP, and be aware of big changes that may impact my workload.*

I think if we decide to skip this page for the email for this year, it needs to be added for V2. One of the major findings in preliminary user research was around the confusion of "what's new/what's changed." This also reduces the amount of questions for central office, and is a more efficient way to communicate changes than the current method of DSCP run Webinars.

**Comment by TaraWilliamsPGH** [comment]
Part of the communications planning.
