### ISSUE TITLE
We need to know which user actions need to be recorded in the database

### ISSUE THREAD

**Issue by ayushi-roy** [18F/cms-carts-seds#152]

**Comment by tadhg-ohiggins** [comment]
Most likely, any user action that changes anything in the database. There's a list of possible Django packages for this here: https://djangopackages.org/grids/g/model-audit/

**Comment by lauraGgit** [comment]
@tadhg-ohiggins do you have any preference between leveraging a logger (duping to stdout) and having some sort of log aggregator or having it be in additional db table.

# Log aggregation
For the log aggregation route, it looks like that we're not using cloud.gov and my cursory look at the terraform modules suggest that the ecs isn't currently sending logs cloudwatch or an elk cluster. If we were to go that route, it looks like we could just use the core python `logging` library, but potentially calling it from a middleware like [django-request-logging](https://github.com/Rhumbix/django-request-logging) so that you wouldn't have to directly call the logger on every method.

# Revision table
If we did want to stick with just using another data table it looks like this django package: [django-reversion](https://django-reversion.readthedocs.io/en/stable/api.html) is pretty much geared toward having a decorator on your models that enables your to set revisions in the table. The drawback is you'd have to probably build another interface to audit the actual revisions (though an sql query would be sufficient). You'd also have to still build out decorators for auditing events like successful/failed authentications, which could still be done via decorators and then just sent to the db.

**Comment by lauraGgit** [comment]
[Tock](https://github.com/18F/tock/blob/main/docs/logging.md) has a good list of what user actions are recorded that would serve as a good base.
