### ISSUE TITLE
Section 3C Build: InputGrid and SynthesizedTable components

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#315]
AC: 

- [x] Build grid from JSON data
- [x] Hide age breakdown fields when toggle is checked
- [ ] ~~Send total values to store~~
- [x] Update SynthesizedTable with total value
- [x] Render from Question Component

Related to #92 3C and 3I.

**Comment by cannandev** [comment]
blocks 3G build #211

**Comment by mgwalker** [comment]
@tadhg-ohiggins One of the acceptance criteria here is "send total values to store" – is that correct? Do computed values get stored back into the JSON somewhere? If so, do they also get persisted back to the API? I was under the assumption that synthesized values were always computed on the fly.

Or if that's wrong, I'll strike out that checkbox. 😛

**Comment by tadhg-ohiggins** [comment]
This was an ongoing question, but yes, I think the total should get sent back, particularly since (unless I'm mistaking this for another case) sometimes states _only_ enter the totals.
The issue this raises is what happens if there are conflicts between these numbers, and I don't think we ever fully worked that out, other than that anything the user enters should probably take precedence even if it conflicts with the math…

**Comment by mgwalker** [comment]
The case where users could enter totals or have them computed has been removed for now. AFAIK, values are either computed or user-editable, but no longer both.

My biggest concern is any difference in the math implementation causing a difference between what a state user saw when they submitted the form and what a CMS user sees when they're reviewing it. But if that's all handled in the frontend for now, I'm content to leave it out of the JSON for now to avoid the extra complexity.

**Comment by cjhskippy** [comment]
The Q of whether we need to save total values to store went back and forth a few times.  Per conversation yesterday, we decided that was NOT needed for this issue, we're going to close this one and work on related functionality in #718
