### ISSUE TITLE
Display Report Status

### ISSUE THREAD

**Issue by cannandev** [18F/cms-carts-seds#418]
As a user, I want to see the correct status of my report while working on it.  This should appear in the header for each section, where it currently says "in progress" in this screenshot:

<img width="631" alt="Screen Shot 2020-09-09 at 7 30 57 PM" src="https://user-images.githubusercontent.com/1299543/92674944-39cd5280-f2d3-11ea-8fa7-57b4cf48a8a1.png">

AC: 
- [x] Show status of the current report as recorded in the database
- [x] Show logged in user's state (is this done? this looks like it's working on localhost)

- [ ] IN A PINCH: Simply HIDE the status so it is not confusing to the user if we cannot meet the above 2 criteria in time

Engineering notes:
- Likely related to the PageInfo component (former issue title: Update <PageInfo> component with API data)
- Will include adding document status to JSON/API

**Comment by heymatthenry** [comment]
A few questions about this: 

1. The ticket mentions the text "in progress" in the screenshot, but that text isn't actually there. Are we talking about where it says "Draft"?
1. If it is the "draft" text, what are the possible statuses?
1. Is the second AC done? I'm not sure which state its referring to.
1. Is the "last edit" timestamp duplicative of the last save timestamp since the form autosaves?

**Comment by StephanieCoppel** [comment]
@heymatthenry 
1. YES it is where the text says draft - it should say in progress (as this is the official name of the status, not draft)
2. the statuses of this document are in progress, certified and submitted, and accepted (workflow mural here: https://app.mural.co/t/upmc4555/m/upmc4555/1601924190266/917889a4d9489374a4f5fd0a043f9ed41f27bb8c). 
3. i'm not sure - i can see mine says massachussetts but i'm not sure additional backend work needs to be done.
4. i'm not sure about this either, and i cant check based on how the site is performing for me right now!
