### ISSUE TITLE
Options Obj. Doesn't Present in Order

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#474]
The Options Object doesn't present in proper order.

**Comment by tadhg-ohiggins** [comment]
Context: the `options` property for a question contains its possible answers, and so applies primarily to radio button and checkbox questions. The issue here is that I used a JSON object, rather than a JSON array, to represent it, and the ordering of keys in JSON objects isn't guaranteed. So a question that has answers of “Yes” and “No” can end up having the order of “No” and “Yes”.
To fix this I should
a) Change all of the values of `options` properties in the JSON from objects to arrays in the right order.
b) Change the relevant code in the questions component so that it knows how to handle the new data structure.
