### ISSUE TITLE
American Community Survey data support

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/cms-carts-seds#477]
State users need to be able to see the American Community Survey data in the start of Section 2.
The data varies per state per year.

For this issue, the data does not need to be user-editable.  That use case is covered in #637 

AC:
- [x] Add location in Redux Store for this. Should be linked to info about the state/state program.
- [x] Add DB spot for this.
- [x] Add API read endpoint.
- [x] Add API write endpoint.
- [x] Add permissions for endpoint.
- [x] Add frontend UI for endpoint OR get data from DSCP directly so that we can enter it, if the frontend for central office users isn't done by then.
- [x] Table in Section 2 Part 2 (first table) is populated with ACS data for the last 5 years (based on example in content doc)
- [x] JSON is updated appropriately to display the data from the new endpoint
- [x] Update README with how this data is loaded to Section 2 Part 2

**Comment by kaitlin** [comment]
This is probably something I can knock out (at least all the backend bits) if it's needed for release. I noticed in 2020-02-a-02 in the base JSON template that it's prefilled with dummy data. We may want to update that JSON to be empty by default in the course of this ticket. 

I also don't think we need permissions on this endpoint, since it's public data anyway?

**Comment by kaitlin** [comment]
Just as a note, I'm noticing that the [HI-10 tables](https://www.census.gov/data/tables/time-series/demo/health-insurance/acs-hi.2019.html) that DSCP uses don't include data for American Samoa (AS), Guam (GU), or the Northern Mariana Islands (MP). They do have data for DC and Puerto Rico. It may not be an issue since I know at least in AS, everyone is eligible for Medicaid so the uninsured rate might not be meaningful.

**Comment by heymatthenry** [comment]
These data made it into Redux along with the FMAP data as part of #717. The data aren't surfaced in the JSON, but each state's ACS data are there in Redux under `allStatesData`.
