### ISSUE TITLE
Section 0 - Help Desk Link (bug)

### ISSUE THREAD

**Issue by cjhskippy** [18F/cms-carts-seds#693]
The help desk link in section zero is appearing as code rather than a clickable link:

<img width="590" alt="Screen Shot 2020-09-28 at 5 23 54 PM" src="https://user-images.githubusercontent.com/1299543/94498671-94115300-01af-11eb-8496-8797fb6ad4cd.png">

**Comment by tadhg-ohiggins** [comment]
We don't really want to allow full HTML rendering of whatever is in the JSON, so I think for this we need a `fieldset_type` of `link`, where the value of `link` is an array of dictionaries with `text` and `url` properties. The frontend would go through the array and find (in the `label` value) the text indicated by the `text` value, then replace it with an `a` element with the appropriate `href`.
Others might have different ideas for this, though.

**Comment by mgwalker** [comment]
Ooh, doing inline (rather than block) fieldsets would be an entirely new thing. There's some complexity there... But I do 100% agree we should not render HTML from the JSON.

My question would be how many places does this occur? If this is the only spot, I might say special case it in the code because that could be faster than changing the JSON. (I.e., if you're in section 0, we manually parse the text to pull out the email address and turn it into a link). If there are more occurrences, though, then it's probably better to update the JSON schema.

(I'm curious why the value would be an array of links instead of just one?)
