### ISSUE TITLE
Wait Spinner for Page Loading

### ISSUE THREAD

**Issue by jgillis1** [18F/cms-carts-seds#768]
As a user, when I navigate to a page I want to see a visual que that the page is loading, particular if it takes a few seconds to load the page so that I know my action request was received and is being processed. 

Example: Section 1 takes several seconds to load

AC:

- [ ] Spinner is shown when the application has requested an action occur and is waiting for a response

**Comment by mgwalker** [comment]
I'm pretty sure there's not a strictly frontend 100% fix for this. The delay is due to JSONPath lookups, which are very costly. For sections with a lot of computed values or conditional displays, it just takes a long time. We do some internal cacheing to speed up subsequent lookups (which makes them literally 1,000 times faster), but we can't pre-cache that information (per se; there may be some options here). It is possible place a spinner on the DOM, but it probably will not animate because the JSONPath lookups are happening on the main thread and blocking the page from repainting.

If the spinner doesn't need to animate, no problem! If it should, then either...

1. Figure out how to make the JSONPath lookups asynchronous and do them in a web worker ([here's a pretty good article](https://medium.com/@bykovskimichael/how-to-use-web-worker-with-create-react-app-e1c1f1ba5279) describing how to load a web worker in a create-react-app configuration; I tried it out and it works a charm). That'll free up the main thread so it can animate the spinner. But this turns into a whole can of worms because some of those lookups are happening in the state reducers, and those ***must*** be synchronous. I hadn't spent much time thinking about how to fix that because it seemed like such a big ball of hair.

...or...

2. Update the `generate_fixtures` utility or the API code to pre-compute the exact paths to synthesized or conditional targets. This doesn't solve the issue of the spinner not animating, but it would dramatically speed up the page load such that maybe the spinner is no longer needed. The headache here is that the Python JSONPath libraries don't generate paths that are compatible with the Javascript JSONPath library, so there would have to be some manual banging on the computed paths to get them to conform to what the frontend can use.

---

It might be possible to save off the cache of exact paths that the `jsonpath` utility wrapper creates and reuse it on subsequent page loads. It can go into local storage and get pulled up on initialization. That helps a ton for any pages the user has previously visited, but the first visit is still slow as Christmas. Furthermore, we'd need to make sure that we handle the case where the shape of the form has changed, which ought to invalidate the cache because we can no longer be sure that the existing path mappings are correct. (I fiddled with this on the [mgwalker/cache-path-lookups branch](https://github.com/18F/cms-carts-seds/compare/mgwalker/cache-path-lookups); I think this is workable for speeding up subsequent page loads, but I didn't have time to go back through the code to make sure it really made sense, so it's still sitting out there, dangling.).
